In [ ]:
Name: Aisha

## import needed libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn import tree, metrics
from sklearn.model_selection import train_test_split

## read the car.data

          0      1      2     3      4     5      6
0     vhigh  vhigh      2     2  small   low  unacc
1     vhigh  vhigh      2     2  small   med  unacc
2     vhigh  vhigh      2     2  small  high  unacc
3     vhigh  vhigh      2     2    med   low  unacc
4     vhigh  vhigh      2     2    med   med  unacc
5     vhigh  vhigh      2     2    med  high  unacc
6     vhigh  vhigh      2     2    big   low  unacc
7     vhigh  vhigh      2     2    big   med  unacc
8     vhigh  vhigh      2     2    big  high  unacc
9     vhigh  vhigh      2     4  small   low  unacc
10    vhigh  vhigh      2     4  small   med  unacc
11    vhigh  vhigh      2     4  small  high  unacc
12    vhigh  vhigh      2     4    med   low  unacc
13    vhigh  vhigh      2     4    med   med  unacc
14    vhigh  vhigh      2     4    med  high  unacc
15    vhigh  vhigh      2     4    big   low  unacc
16    vhigh  vhigh      2     4    big   med  unacc
17    vhigh  vhigh      2     4    big  high  unacc
18    vhigh  vhigh      2  more  small   low  unacc
19    vhigh  vhigh      2  more  small   med  unacc
20    vhigh  vhigh      2  more  small  high  unacc
21    vhigh  vhigh      2  more    med   low  unacc
22    vhigh  vhigh      2  more    med   med  unacc
23    vhigh  vhigh      2  more    med  high  unacc
24    vhigh  vhigh      2  more    big   low  unacc
25    vhigh  vhigh      2  more    big   med  unacc
26    vhigh  vhigh      2  more    big  high  unacc
27    vhigh  vhigh      3     2  small   low  unacc
28    vhigh  vhigh      3     2  small   med  unacc
29    vhigh  vhigh      3     2  small  high  unacc
...     ...    ...    ...   ...    ...   ...    ...
1698    low    low      4  more    big   low  unacc
1699    low    low      4  more    big   med   good
1700    low    low      4  more    big  high  vgood
1701    low    low  5more     2  small   low  unacc
1702    low    low  5more     2  small   med  unacc
1703    low    low  5more     2  small  high  unacc
1704    low    low  5more     2    med   low  unacc
1705    low    low  5more     2    med   med  unacc
1706    low    low  5more     2    med  high  unacc
1707    low    low  5more     2    big   low  unacc
1708    low    low  5more     2    big   med  unacc
1709    low    low  5more     2    big  high  unacc
1710    low    low  5more     4  small   low  unacc
1711    low    low  5more     4  small   med    acc
1712    low    low  5more     4  small  high   good
1713    low    low  5more     4    med   low  unacc
1714    low    low  5more     4    med   med   good
1715    low    low  5more     4    med  high  vgood
1716    low    low  5more     4    big   low  unacc
1717    low    low  5more     4    big   med   good
1718    low    low  5more     4    big  high  vgood
1719    low    low  5more  more  small   low  unacc
1720    low    low  5more  more  small   med    acc
1721    low    low  5more  more  small  high   good
1722    low    low  5more  more    med   low  unacc
1723    low    low  5more  more    med   med   good
1724    low    low  5more  more    med  high  vgood
1725    low    low  5more  more    big   low  unacc
1726    low    low  5more  more    big   med   good
1727    low    low  5more  more    big  high  vgood

[1728 rows x 7 columns]

In [3]:
filename="car.data"
data=pd.read_csv(filename, delimiter=',',index_col=False,names=[0,1,2,3,4,5,6])
#GET ALL DATA
data

          0      1      2     3      4     5      6
0     vhigh  vhigh      2     2  small   low  unacc
1     vhigh  vhigh      2     2  small   med  unacc
2     vhigh  vhigh      2     2  small  high  unacc
3     vhigh  vhigh      2     2    med   low  unacc
4     vhigh  vhigh      2     2    med   med  unacc
...     ...    ...    ...   ...    ...   ...    ...
1723    low    low  5more  more    med   med   good
1724    low    low  5more  more    med  high  vgood
1725    low    low  5more  more    big   low  unacc
1726    low    low  5more  more    big   med   good
1727    low    low  5more  more    big  high  vgood

[1728 rows x 7 columns]

In [5]:
xarr = np.array(data)
X = data.iloc[:, :-1].values
y = data.iloc[:,-1:]
numFeatures = X.shape[1] #6
numFeatures
y

          6
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]



## do the preprocessing

In [4]:
#for dec tree we need int but we have object
data[0],_ = pd.factorize(data[0])
data[1],_ = pd.factorize(data[1])
data[2],_ = pd.factorize(data[2])
data[3],_ = pd.factorize(data[3])
data[4],_ = pd.factorize(data[4])
data[5],_ = pd.factorize(data[5])
#y
data[6],oury = pd.factorize(data[6])

data

      0  1  2  3  4  5  6
0     0  0  0  0  0  0  0
1     0  0  0  0  0  1  0
2     0  0  0  0  0  2  0
3     0  0  0  0  1  0  0
4     0  0  0  0  1  1  0
...  .. .. .. .. .. .. ..
1723  3  3  3  2  1  1  3
1724  3  3  3  2  1  2  2
1725  3  3  3  2  2  0  0
1726  3  3  3  2  2  1  3
1727  3  3  3  2  2  2  2

[1728 rows x 7 columns]

In [5]:
numericX = data.iloc[:, :-1].values
numericY = data.iloc[:,-1:].values
#numericY = np.array(numericY)
numericY

array([[0],
       [0],
       [0],
       ...,
       [0],
       [3],
       [2]], dtype=int64)

In [8]:
#imputer = SimpleImputer(missing_values=np.nan, strategy='constant')
#imputer = imputer.fit(X[:,1:3])
#X[:, 1:3] = imputer.transform(X[:, 1:3])
#X


## Apply Decision Tree Algorithm
You can use sklearn
As usual, divide the dataset for train and test

In [9]:
def traintest():
    return train_test_split(numericX, numericY, test_size=0.30, random_state=0)

x_train, x_test, y_train, y_test = traintest()
traintest()
x_train
y_train=np.array(y_train)
len(x_train),len(x_test)

(1209, 519)

In [10]:
#code from lection
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier(criterion='entropy',max_depth=3,random_state=0)
tree.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)

In [ ]:
#from mlxtend.plotting import plot_decision_regions
#x_comb=np.vstack((x_train,x_test))
#y_comb=np.hstack((y_train,y_test))
#plot_decision_regions(x_comb,y_comb,clf=tree)

Accuracy is about  0.9826589595375722 %

In [12]:
#Accuracy num of correct pred divided by the total numb of pred.

#correct accuracy
tree2 = DecisionTreeClassifier()
tree2 = tree2.fit(x_train,y_train)
pred = tree2.predict(x_test)
acc2 = accuracy_score(y_test, pred)
print('Accuracy',acc2)


#accuracy with decision tree entropy
ypred = tree.predict(x_test)
acc = accuracy_score(y_test, ypred)
print('Accuracy is about',acc,'%')


#2 variant with cof matrix
def perf_measure(y_actual, y_pred):
    TP = 0
    FP = 0
    TN = 0
    FN = 0
    for i in range(len(y_pred)): 
        if y_actual[i]==y_pred[i]==1:
           TP += 1
        if y_pred[i]==1 and y_actual[i]!=y_pred[i]:
           FP += 1
        if y_actual[i]==y_pred[i]==0:
           TN += 1
        if y_pred[i]==0 and y_actual[i]!=y_pred[i]:
           FN += 1
    #return(TP, FP, TN, FN)
    return ((TP+TN)/(TP+TN+FP+FN))*100

print('Accuracy with my own accuracy function',perf_measure(y_test,ypred),'%')

Accuracy 0.9710982658959537
Accuracy is about 0.815028901734104 %
Accuracy with my own accuracy function 81.5028901734104 %

## Write your own function for f1-score

F1 score is about:  0.896551724137931  %

In [13]:
def functf1(y_actual, y_pred):
    TP = 0
    FP = 0
    TN = 0
    FN = 0
    for i in range(len(y_pred)): 
        if y_actual[i]==y_pred[i]==1:
           TP += 1
        if y_pred[i]==1 and y_actual[i]!=y_pred[i]:
           FP += 1
        if y_actual[i]==y_pred[i]==0:
           TN += 1
        if y_pred[i]==0 and y_actual[i]!=y_pred[i]:
           FN += 1
    #return(TP, FP, TN, FN)
    P=TP/TP+FP
    R=TP/P
    #R=TP/FN+TP
    return 2*P*R/P+R

print('F1 score is about:',functf1(y_train,ypred),'%')

F1 score is about: 0.9183673469387755 %